### PR TITLE
add auto update feature

### PR DESCRIPTION
**Pull request by musou1500**
It works on dev-master version of https://github.com/padawan-php/deoplete-padawan.php .
But, at the moment, so vim shows error below because update command returns no content.
`Padawa.php error: Expecting value line 1 column 1 (char 0)`

### CODE REVIEW

**Comment by musou1500** [comment]
It will fixes #17

**Comment by musou1500** [comment]
Thanks of this commit (https://github.com/padawan-php/padawan.php/commit/4611c3a0dc73b7e907e25ac8765568b1da364fa8), I could confirm it working well .

**Comment by pbogut** [comment]
Thanks @musou1500, looks very good. Even with error in older padawan version it is working all right.
As it's an option disabled by default I'm happy to merge it.

Care to add it to the ~documentation~ README.md before we merge?

**Comment by musou1500** [comment]
Thanks. I added explanation for new `g:deoplete#sources#padawan#auto_update` option.

**Comment by pbogut** [comment]
Merged. Thank you for the contribution :slightly_smiling_face:

**Pull request merged**
