### PR TITLE
Fixed headers of request

### PR DESCRIPTION
**Pull request by mkusher**

### CODE REVIEW

**Comment by pbogut** [comment]
Are you sure this is working? This plugin is using python3 and as far as I'm aware there is no urllib2 module in python3.

**Comment by mkusher** [comment]
oops, let me test then properly :)

**Comment by mkusher** [comment]
@pbogut yeah, you're right, fixed it

**Comment by pbogut** [comment]
Thanks, I will check it on the weekend.

**Comment by mkusher** [comment]
@pbogut ok, it should now work with master version of padawan as well as with 0.2

**Pull request merged**
